example:
  property: 'I AM DEV'
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost/8070/eureka/}

spring:
  datasource:
    url: 'jdbc:postgresql://database:5432/ostock_dev'
    username: 'postgres'
    password: '{cipher}f4609209a3e75d8ac79a5e3063ce151c2cd28aa431170bb06974b9421e807b6a'
management:
  endpoint:
    env:
      show-values: 'ALWAYS'
    health:
      show-details: 'always'
param: 'param'