example:
  property: 'I AM DEV'
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
    hostname: eurekaserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  datasource:
    url: 'jdbc:postgresql://database:5432/ostock_dev'
    username: 'postgres'
    password: 'postgres'
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  endpoint:
    env:
      show-values: 'ALWAYS'
    health:
      show-details: 'always'